---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation


name: "️Gerrit change request information"
description: "Gerrit change request information"

inputs:
  gerrit_change_url:
    description: "Gerrit Change URL"
    required: true
  gerrit_patchset_number:
    description: "Patchset Number (optional)"
    required: false

outputs:
  gerrit_branch:
    description: "Gerrit branch name"
    value: ${{ steps.gerrit.outputs.GERRIT_BRANCH }}
  gerrit_change_id:
    description: "Gerrit change ID"
    value: ${{ steps.gerrit.outputs.GERRIT_CHANGE_ID }}
  gerrit_change_url:
    description: "Gerrit change URL"
    value: ${{ steps.gerrit.outputs.GERRIT_CHANGE_URL }}
  gerrit_change_number:
    description: "Gerrit change number"
    value: ${{ steps.gerrit.outputs.GERRIT_CHANGE_NUMBER }}
  gerrit_event_type:
    description: "Event type (hardcoded as comment_added)"
    value: ${{ steps.gerrit.outputs.GERRIT_EVENT_TYPE }}
  gerrit_patchset_number:
    description: "Patchset number"
    value: ${{ steps.gerrit.outputs.GERRIT_PATCHSET_NUMBER }}
  gerrit_patchset_revision:
    description: "Patchset revision SHA"
    value: ${{ steps.gerrit.outputs.GERRIT_PATCHSET_REVISION }}
  gerrit_project:
    description: "Gerrit project name"
    value: ${{ steps.gerrit.outputs.GERRIT_PROJECT }}
  gerrit_refspec:
    description: "Refspec for the patchset"
    value: ${{ steps.gerrit.outputs.GERRIT_REFSPEC }}
  gerrit_hostname:
    description: "Gerrit server hostname"
    value: ${{ steps.gerrit.outputs.GERRIT_HOSTNAME }}

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install jq
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Run Gerrit Query (API)
      id: gerrit
      shell: bash
      run: |
        chmod a+x .github/scripts/gerrit_api_query.sh
        .github/scripts/gerrit_api_query.sh "${{ inputs.gerrit_change_url }}" \
            "${{ inputs.gerrit_patchset_number }}"

        # Export Gerrit outputs
        if [ -f "${GERRIT_CHANGE_ID}.file" ]; then
          while IFS= read -r line; do
            echo "$line" >> "$GITHUB_OUTPUT"
          done < "${GERRIT_CHANGE_ID}.file"
        fi

    - name: "Verify Gerrit Change Id"
      shell: bash
      run: |
        if [[ -z "${{ steps.gerrit.outputs.GERRIT_CHANGE_ID }}" ]]; then
          echo "Error: Gerrit query failed or change not found."
          exit 1
        fi

    - name: "Validate file output"
      shell: bash
      run: |
        gerrit_change_id="${{ steps.gerrit.outputs.GERRIT_CHANGE_ID }}
        if [ ! -f "$gerrit_change_id".file ]; then
          echo "Missing file output"
          exit 1
        fi
