---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Action test/validation workflow
name: "Test GitHub Action 🧪"

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions: {}

jobs:
  ### Test the GitHub Action in this Repository ###
  tests:
    name: "Test local GitHub Action"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 5
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: "Checkout Gerrit Change Info repository"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: "lfreleng-actions/gerrit-change-info"
          path: "gerrit-change-info"

      # Disable test to continue on error, until ssh keys are configured
      - name: "Running local action: ${{ github.repository }}"
        uses: ./
        with:
          # yamllint disable-line rule:line-length
          gerrit_change_url: "https://git.opendaylight.org/gerrit/c/releng/builder/+/111445"
          gerrit_patchset_number: "6"
          ssh_user_name: "${{ vars.GERRIT_SSH_USER }}"
          ssh_private_key: "${{ secrets.GERRIT_SSH_KEY }}"
        continue-on-error: true

      - name: "Validating local action: ${{ github.repository }}"
        shell: bash
        run: |
          # Local action validation
          echo "Validating local action: ${{ github.repository }}"
          echo "Validation step summary output" >> "$GITHUB_STEP_SUMMARY"

      - name: SSH Key Error Test
        uses: ./
        with:
          # yamllint disable-line rule:line-length
          gerrit_change_url: "https://gerrit.example.org/c/sample-project/+/12345"
          ssh_user_name: "jenkins"
          ssh_private_key: ""
        continue-on-error: true

      - name: SSH Key Error Test
        uses: ./
        with:
          # yamllint disable-line rule:line-length
          gerrit_change_url: "https://gerrit.example.org/c/sample-project/+/12345"
          ssh_user_name: "jenkins"
          ssh_private_key: ""
        continue-on-error: true
